#!/bin/sh

BRANCH=`git branch | grep '^*' | sed -e 's/^\* //' | tr 'a-z' 'A-Z'|cut -d '/' -f 2`
MESSAGE=`cat "$1"`
# проверки нужны, чтобы не добавлять к уже существующему префиксу с названием бранча новый префикс
# во время 
#  commit --amend
#  rebase -i
#  cherry-pick
if [[ ! ${MESSAGE} =~ [A-Z0-9_-]+:\ .* ]] && [[ ! -d "$GIT_DIR"/rebase-merge ]] && 
	[[ ! -d "$GIT_DIR"/rebase-apply ]] && [[ ! -d "$GIT_DIR"/sequencer ]]; then
	echo "$BRANCH: $MESSAGE" > "$1"
fi
